version: "3.3"
services:
  seafile:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    image: nikoglyph/seafile-server
    ports:
        - "443:443"
    environment:
        - SEAFILE_EXTERNAL_PORT=443
        - SEAFILE_HOSTNAME=localhost
        - SEAFILE_SERVER_NAME=myseafile
        - SEAFILE_ADMIN_MAIL=admin@seafile.com
        - SEAFILE_ADMIN_PASSWORD=test123
        - USE_SSL=on
    volumes:
      - type: bind
        source: /tmp/seafile
        target: /data
      - type: bind
        read_only:
        source: ~/ssl
        target: /etc/ssl
